sudo: false
language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - pip install -U pip
  - pip install poetry
install:
  - poetry install
script:
  - python setup.py nosetests --with-coverage
services:
  - mongodb
after_success:
  - codecov